# Generated by Django 5.2.16 on 2026-07-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_seen', 'username']},
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
