# Generated by Django 5.2.16 on 2026-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_add_topic_created_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
