# Generated by Django 5.2.16 on 2026-07-26 16:54

from django.db import migrations, models


def copy_created_to_updated(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    Topic.objects.all().update(updated=models.F('created'))


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_updated'),
    ]

    operations = [
        migrations.RunPython(copy_created_to_updated, reverse_code=migrations.RunPython.noop),
    ]
