# Generated by Django 5.2.16 on 2026-07-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_copy_created_to_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
