# Generated by Django 5.2.16 on 2026-07-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_reply_max_length_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reply',
            new_name='core_reply_created_7391ca_idx',
            old_name='forum_reply_created_aa01_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='core_reply_topic_i_4621f1_idx',
            old_name='forum_reply_topic_created_aa02_idx',
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(),
        ),
    ]
