# Generated by Django 5.2.16 on 2026-07-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.reply')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_likes',
                'indexes': [models.Index(fields=['topic'], name='core_likes_topic_i_7bdd54_idx'), models.Index(fields=['reply'], name='core_likes_reply_i_cd0972_idx'), models.Index(fields=['user', 'created'], name='core_likes_user_id_cd14bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic_like'), models.UniqueConstraint(fields=('user', 'reply'), name='unique_user_reply_like')],
            },
        ),
    ]
