# Generated by Django 5.2.16 on 2026-07-24 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0003_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['content_type', 'object_id'], name='interaction_content_914492_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['user', 'created'], name='interaction_user_id_042173_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_share'),
        ),
    ]
